// <auto-generated />
using System;
using Auto_Shop.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auto_Shop.Infra.Data.Migrations
{
    [DbContext(typeof(AutoShopContext))]
    [Migration("20230328201657_SeedChanges")]
    partial class SeedChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Auto_Shop.Domain.Models.Brand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("AS_BRANDS");

                    b.HasData(
                        new
                        {
                            Id = "4d658abf",
                            Description = "Ford Motor Company is an American multinational automobile manufacturer.",
                            ImageUrl = "http://site.com.br",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(2042),
                            Name = "Ford"
                        },
                        new
                        {
                            Id = "b65f24df",
                            Description = "Honda Motor Co., Ltd. is a Japanese public multinational conglomerate manufacturer of automobiles.",
                            ImageUrl = "http://site.com.br",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(2788),
                            Name = "Honda"
                        },
                        new
                        {
                            Id = "5d953bd2",
                            Description = "Toyota Motor Corporation is a Japanese multinational automotive manufacturer headquartered in Toyota City, Aichi, Japan.",
                            ImageUrl = "http://site.com.br",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(2795),
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = "64af3255",
                            Description = "Fiat Automobiles S.p.A. is an Italian automobile manufacturer, formerly part of Fiat Chrysler Automobiles.",
                            ImageUrl = "http://site.com.br",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(2800),
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = "393dd12c",
                            Description = "Volkswagen AG, known internationally as the Volkswagen Group, is a German multinational automotive manufacturer.",
                            ImageUrl = "http://site.com.br",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(2804),
                            Name = "Volkswagen"
                        });
                });

            modelBuilder.Entity("Auto_Shop.Domain.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AS_ROLES");

                    b.HasData(
                        new
                        {
                            Id = "f3016a70",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(4921),
                            RoleName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Auto_Shop.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RoleId")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AS_USERS");

                    b.HasData(
                        new
                        {
                            Id = "de3da888",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(5238),
                            Password = "1AbYhcg*!@3",
                            RoleId = "f3016a70",
                            Username = "adm@adm.com"
                        });
                });

            modelBuilder.Entity("Auto_Shop.Domain.Models.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("http://");

                    b.Property<string>("Km")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("AS_VEHICLES");

                    b.HasData(
                        new
                        {
                            Id = "4a518449",
                            BrandId = "4d658abf",
                            City = "São Paulo",
                            ImageUrl = "http://site.com.br",
                            Km = "69.752",
                            Model = "Sedan",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(3035),
                            Name = "Ford Focus",
                            Price = 62.900m,
                            State = "SP",
                            Year = "2015"
                        },
                        new
                        {
                            Id = "2c00bee7",
                            BrandId = "b65f24df",
                            City = "Rio de Janeiro",
                            ImageUrl = "http://site.com.br",
                            Km = "54.000",
                            Model = "Sedan",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(4717),
                            Name = "Honda Civic",
                            Price = 135.000m,
                            State = "RJ",
                            Year = "2020"
                        },
                        new
                        {
                            Id = "8fbc6dc7",
                            BrandId = "5d953bd2",
                            City = "Niterói",
                            ImageUrl = "http://site.com.br",
                            Km = "111.040",
                            Model = "Sedan",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(4726),
                            Name = "Toyota Corolla",
                            Price = 71.900m,
                            State = "RJ",
                            Year = "2013/2014"
                        },
                        new
                        {
                            Id = "7b78baf7",
                            BrandId = "64af3255",
                            City = "Santos",
                            ImageUrl = "http://site.com.br",
                            Km = "82.000",
                            Model = "Hatchback",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(4735),
                            Name = "Fiat Uno",
                            Price = 42.990m,
                            State = "SP",
                            Year = "2015"
                        },
                        new
                        {
                            Id = "e9cfa31f",
                            BrandId = "393dd12c",
                            City = "Brasília",
                            ImageUrl = "http://site.com.br",
                            Km = "23.652",
                            Model = "Sport Utility",
                            ModifiedOn = new DateTime(2023, 3, 28, 17, 16, 57, 291, DateTimeKind.Local).AddTicks(4739),
                            Name = "Volkswagen Nivus",
                            Price = 121.000m,
                            State = "DF",
                            Year = "2020/2021"
                        });
                });

            modelBuilder.Entity("Auto_Shop.Domain.Models.Vehicle", b =>
                {
                    b.HasOne("Auto_Shop.Domain.Models.Brand", "Brand")
                        .WithMany("Vehicles")
                        .HasForeignKey("BrandId")
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Auto_Shop.Domain.Models.Brand", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
