// <auto-generated />
using System;
using Auto_Shop.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auto_Shop.Infra.Data.Migrations
{
    [DbContext(typeof(AutoShopContext))]
    [Migration("20230120233853_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Auto_Shop.Domain.Models.Brand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("AS_BRANDS");

                    b.HasData(
                        new
                        {
                            Id = "42cebc4a",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(629),
                            Description = "Ford Motor Company is an American multinational automobile manufacturer.",
                            ImageUrl = "http://site.com.br",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = "5df6d900",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(1361),
                            Description = "Honda Motor Co., Ltd. is a Japanese public multinational conglomerate manufacturer of automobiles.",
                            ImageUrl = "http://site.com.br",
                            Name = "Honda"
                        },
                        new
                        {
                            Id = "e91aff9b",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(1368),
                            Description = "Toyota Motor Corporation is a Japanese multinational automotive manufacturer headquartered in Toyota City, Aichi, Japan.",
                            ImageUrl = "http://site.com.br",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = "cea2e390",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(1372),
                            Description = "Fiat Automobiles S.p.A. is an Italian automobile manufacturer, formerly part of Fiat Chrysler Automobiles.",
                            ImageUrl = "http://site.com.br",
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = "ed218cbd",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(1388),
                            Description = "Volkswagen AG, known internationally as the Volkswagen Group, is a German multinational automotive manufacturer.",
                            ImageUrl = "http://site.com.br",
                            Name = "Volkswagen"
                        });
                });

            modelBuilder.Entity("Auto_Shop.Domain.Models.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BrandName")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("http://");

                    b.Property<string>("Km")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("AS_VEHICLES");

                    b.HasData(
                        new
                        {
                            Id = "b3a14b02",
                            BrandId = "42cebc4a",
                            City = "São Paulo",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(1560),
                            ImageUrl = "http://site.com.br",
                            Km = "69.752",
                            Model = "Sedan",
                            Name = "Ford Focus",
                            Price = 62.900m,
                            State = "SP",
                            Year = "2015"
                        },
                        new
                        {
                            Id = "ae184287",
                            BrandId = "5df6d900",
                            City = "Rio de Janeiro",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(3173),
                            ImageUrl = "http://site.com.br",
                            Km = "54.000",
                            Model = "Sedan",
                            Name = "Honda Civic",
                            Price = 135.000m,
                            State = "RJ",
                            Year = "2020"
                        },
                        new
                        {
                            Id = "a886df53",
                            BrandId = "e91aff9b",
                            City = "Niterói",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(3181),
                            ImageUrl = "http://site.com.br",
                            Km = "111.040",
                            Model = "Sedã",
                            Name = "Toyota Corolla",
                            Price = 71.900m,
                            State = "RJ",
                            Year = "2013/2014"
                        },
                        new
                        {
                            Id = "cf5d60b9",
                            BrandId = "cea2e390",
                            City = "Santos",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(3186),
                            ImageUrl = "http://site.com.br",
                            Km = "82.000",
                            Model = "Hatchback",
                            Name = "Fiat Uno",
                            Price = 42.990m,
                            State = "SP",
                            Year = "2015"
                        },
                        new
                        {
                            Id = "0b0892c5",
                            BrandId = "ed218cbd",
                            City = "Brasília",
                            CreatedOn = new DateTime(2023, 1, 20, 20, 38, 53, 163, DateTimeKind.Local).AddTicks(3190),
                            ImageUrl = "http://site.com.br",
                            Km = "23.652",
                            Model = "Sport Utility",
                            Name = "Volkswagen Nivus",
                            Price = 121.000m,
                            State = "DF",
                            Year = "2020/2021"
                        });
                });

            modelBuilder.Entity("Auto_Shop.Domain.Models.Vehicle", b =>
                {
                    b.HasOne("Auto_Shop.Domain.Models.Brand", "Brand")
                        .WithMany("Vehicles")
                        .HasForeignKey("BrandId")
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Auto_Shop.Domain.Models.Brand", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
